### ISSUE TITLE
`$git.LatestTag` is empty when compiling from GitHub Actions

### ISSUE THREAD

**Issue by littensy** [roblox-aurora/rbxts-transform-debug#14]
When I try to use `$git.LatestTag` via GitHub Actions, it compiles to a blank string when it shouldn't.

I experience this issue in my own game, which has a workflow that deploys the place file when a commit is pushed to the main branch. In this case, `$git.LatestTag` is always an empty string. When I compile my game locally, it works correctly.

**Comment by Vorlias** [comment]
It uses a git command to grab this information, so it's possible for one reason or another git hasn't got the tags available to it.

See:
https://stackoverflow.com/questions/1404796/how-can-i-get-the-latest-tag-name-in-current-branch-in-git#7261049

You can probably try running these in your actions to see if one over the other works, if not it's possible that action isn't pulling the tags when it pulls the repo.

If I recall correctly, this transformer uses the `git describe --abbrev=0` command

**Comment by Vorlias** [comment]
Can you run the commands in https://stackoverflow.com/questions/1404796/how-can-i-get-the-latest-tag-name-in-current-branch-in-git#7261049 in the action? Curious if it's a git issue (like not pulling the tags) or the library the transformer is using

**Comment by littensy** [comment]
> Can you run the commands in https://stackoverflow.com/questions/1404796/how-can-i-get-the-latest-tag-name-in-current-branch-in-git#7261049 in the action? Curious if it's a git issue (like not pulling the tags) or the library the transformer is using

I tried to use the commands from within an action, but it threw an error. This seems to be an issue with GitHub Actions creating a shallow clone of the repo without tag history in the checkout step.

<img width="1035" alt="image" src="https://github.com/roblox-aurora/rbxts-transform-debug/assets/56808540/dba384f6-7121-4ea2-acb3-befb9b7214e8">

```yml
steps:
  - uses: actions/checkout@v3
  - uses: bahmutov/npm-install@v1
  - uses: ok-nick/setup-aftman@v0.3.0
    with:
      token: ${{ secrets.GITHUB_TOKEN }}

  - name: Output tag
    run: |
      git describe --tags --abbrev=0
      git describe --tags
      git describe --abbrev=0
```

**Comment by littensy** [comment]
I resolved this issue by adding the following to my checkout step:
```yml
- uses: actions/checkout@v3
  with:
    fetch-tags: true
    fetch-depth: 0
```
Thanks for the heads-up!
